CREATE TABLE OKL.OKL_CLIENTE
(CPF INT PRIMARY KEY,
NOME VARCHAR(64),
ENDERECO VARCHAR(128),
FONE_CLIENTE INT);

CREATE TABLE OKL.OKL_VENDEDOR
(COD_VENDEDOR INT PRIMARY KEY,
NOME_VENDEDOR VARCHAR(64));

CREATE TABLE OKL.OKL_PEDIDO(
    NUMERO_PEDIDO INT PRIMARY KEY,
    CPF INT,
    DATA_PEDIDO DATE,
    DATA_ENTREGA DATE,
    FOREIGN KEY (CPF) REFERENCES OKL.OKL_CLIENTE(CPF)
);

CREATE TABLE OKL.OKL_ITEM_PEDIDO
(NUMERO_ITEM INT PRIMARY KEY,
NUMERO_PEDIDO INT,
COD_PRODUTO INT,
QTD_VENDIDA INT,
VALOR_VENDA REAL,
COD_VENDEDOR INT,
FOREIGN KEY(NUMERO_PEDIDO) REFERENCES OKL.OKL_PEDIDO(NUMERO_PEDIDO),
--FOREIGN KEY(COD_PRODUTO) REFERENCES OKL.OKL_PRODUTO(COD_PRODUTO),
FOREIGN KEY(COD_VENDEDOR) REFERENCES OKL.OKL_VENDEDOR(COD_VENDEDOR));

CREATE TABLE OKL.OKL_PRODUTO(
    COD_PRODUTO INT PRIMARY KEY,
    DESCRICAO_PRODUTO VARCHAR(128),
    PRECO_BASE REAL,
    QTD_ESTOQUE INT,
    --COD_GRUPO INT,
    --FOREIGN KEY (COD_GRUPO) REFERENCES OKL.OKL_ITEM_PEDIDO(COD_GRUPO)
);

ALTER TABLE OKL.OKL_ITEM_PEDIDO
ADD CONSTRAINT ITEM_PRODUTO_PRODUTO_FK FOREIGN KEY(COD_PRODUTO) REFERENCES OKL.OKL_PRODUTO(COD_PRODUTO);