-- Drop tables
DROP TABLE OKL.OKL_ITEM_PEDIDO;
DROP TABLE OKL.OKL_PRODUTO;
DROP TABLE OKL.OKL_CLIENTE;
DROP TABLE OKL.OKL_VENDEDOR;
DROP TABLE OKL.OKL_PEDIDO;

-- Drop triggers
DROP TRIGGER OKL.OKL_trigger_valor_venda;

-- Deletar linhas em específico
DELETE FROM OKL.OKL_PRODUTO
WHERE COD_PRODUTO = 5;

-- Verifica se deletou tudo
SELECT * FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA='OKL';

SELECT * FROM sys.triggers
WHERE name LIKE 'OKL_%';

