CREATE FUNCTION OKL.cliente_status (@cpf CHAR(11)) RETURNS VARCHAR(6) AS
BEGIN
    IF (SELECT SUM(QTD_VENDIDA * VALOR_VENDA) FROM OKL.OKL_ITEM_PEDIDO
        WHERE OKL.OKL_ITEM_PEDIDO.NUMERO_PEDIDO
            IN(SELECT NUMERO_PEDIDO FROM OKL.OKL_PEDIDO
            WHERE CPF = @cpf)) > 5000
    BEGIN
        RETURN('vip');
    END;
    RETURN('normal')
END;

