--DROP ALL
DROP TABLE OKL.OKL_ITEM_PEDIDO;
DROP TABLE OKL.OKL_PRODUTO;
DROP TABLE OKL.OKL_VENDEDOR;
DROP TABLE OKL.OKL_PEDIDO;
DROP TABLE OKL.OKL_CLIENTE;

--CREATE TABLES
CREATE TABLE OKL.OKL_CLIENTE
(CPF CHAR(11) PRIMARY KEY,
NOME VARCHAR(64),
ENDERECO VARCHAR(128),
FONE_CLIENTE CHAR(11));

CREATE TABLE OKL.OKL_VENDEDOR
(COD_VENDEDOR INT PRIMARY KEY,
NOME_VENDEDOR VARCHAR(64));

CREATE TABLE OKL.OKL_PEDIDO(
    NUMERO_PEDIDO INT PRIMARY KEY,
    CPF CHAR(11),
    DATA_PEDIDO DATE,
    DATA_ENTREGA DATE,
    FOREIGN KEY (CPF) REFERENCES OKL.OKL_CLIENTE(CPF)
);

CREATE TABLE OKL.OKL_ITEM_PEDIDO
(NUMERO_ITEM INT PRIMARY KEY,
NUMERO_PEDIDO INT,
COD_PRODUTO INT,
QTD_VENDIDA INT,
VALOR_VENDA REAL,
COD_VENDEDOR INT,
FOREIGN KEY(NUMERO_PEDIDO) REFERENCES OKL.OKL_PEDIDO(NUMERO_PEDIDO),
FOREIGN KEY(COD_VENDEDOR) REFERENCES OKL.OKL_VENDEDOR(COD_VENDEDOR));

CREATE TABLE OKL.OKL_PRODUTO(
    COD_PRODUTO INT PRIMARY KEY,
    DESCRICAO_PRODUTO VARCHAR(128),
    PRECO_BASE REAL,
    QTD_ESTOQUE INT,
);

ALTER TABLE OKL.OKL_ITEM_PEDIDO
ADD CONSTRAINT ITEM_PRODUTO_PRODUTO_FK FOREIGN KEY(COD_PRODUTO) REFERENCES OKL.OKL_PRODUTO(COD_PRODUTO);

--Populate all
INSERT
INTO OKL.OKL_PRODUTO
VALUES
(0, 'Um prod espetacular', 2.0, 200),
(1, 'Um prod excelente', 3.0, 200),
(2, 'Um prod louco', 99.0, 200),
(3, 'Um prod bom', 128.0, 10),
(4, 'Um prod sensacional', 300000000.0, 1);

INSERT INTO OKL.OKL_CLIENTE
VALUES
    ('95693152618', 'Bruna Isabelle Daiane Caldeira', 'Rua OP-IX', '95985783637'),
    ('50539992607', 'Andr¨¦ Juan Ara¨²jo', 'Travessa Benjamin Constant', '79981253309'),
    ('48564804808', 'Diego Matheus Barbosa', 'Rua Severino Francisco dos Santos', '83998001344'),
    ('78379403932', 'Marlene Rayssa Gomes', 'Rua Ademar Jos¨¦ Demate Filho', '47988993243'),
    ('43032367646', 'Elaine Let¨ªcia Alessandra da Cunha', 'Rua Jos¨¦ de Assis R¨¦gis', '83992678421');

INSERT INTO OKL.OKL_VENDEDOR
VALUES
    (0, 'Edson Marcelo Pietro das Neves'),
    (1, 'Fl¨¢via Liz da Luz'),
    (2, 'Antonio Alexandre Theo Castro'),
    (3, 'Raquel Vit¨®ria Novaes'),
    (4, 'Ben¨ªcio Caio Nascimento');